[package]
name = "caribou-window"
version.workspace = true
edition.workspace = true
repository.workspace = true
description = "Windowing system for Caribou: xwindow's window API"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[build-dependencies]
xwindow-backend = { workspace = true }
xwindow-bindgen = { workspace = true }

[dependencies]
caribou_abi = { workspace = true }
xwindow-core = { workspace = true }

# A desktop's windows.
[target.'cfg(not(target_os = "wasi"))'.dependencies]
winit = "0.30"
raw-window-handle = "0.6"
